SuperteamDAO/earn

- components/home/Banner.tsx
- components/listings/listings/details/detailSideCardBounty.tsx
- components/misc/listingsCard.tsx
- components/modals/Login/ConnectWallet.tsx
- components/modals/Login/Login.tsx
- pages/listings/grants/[id].tsx
- https://linear.app/superteam-ops/issue/SUP-1667/number-of-submissions-ui-fix-the-8-here-is-too-close-to-the-briefcase
- https://linear.app/superteam-ops/issue/SUP-1615/replace-pfps-in-the-homepage-sign-up-banner-with-superteam-member-pfps
- https://linear.app/superteam-ops/issue/SUP-1637/grant-submit-now-button-only-opens-the-grant-form-if-the-text-in-it-is
- https://linear.app/superteam-ops/issue/SUP-1597/view-all-button-shows-up-under-view-all-pages-ie-all-bountiesjobs
- https://linear.app/superteam-ops/issue/SUP-1630/create-tooltip-for-talent-in-sign-up-flow-to-remind-them-to-use-their
- https://linear.app/superteam-ops/issue/SUP-1595/make-the-log-in-modal-cancellable
> fix bug fixes

- components/home/SideBar.tsx
https://linear.app/superteam-ops/issue/SUP-1689/clicking-on-create-a-new-profile-from-the-homepage-as-a-logged-out
> fix: default commit

- components/TalentBio/index.tsx
- pages/t/[slug].tsx
https://linear.app/superteam-ops/issue/SUP-1538/keep-my-info-private-checkbox-not-working-properly-ticked-it-although
> fix: changes

- constants/index.ts
- interface/submission.ts
- pages/api/submission/addPayment.ts
- pages/api/user/create.ts
- pages/dashboard/bounties/[slug]/submissions.tsx
- utils/contract/contract.ts
- utils/contract/program.ts
> feat: added payput

- src/components/modals/submissionModalBounty.tsx
On bounty submission, update the error message to `Character limit exceeded. Please reduce the text` when there is 0 characters left.
Checkout the submission modal bounty
Try submitting a bounty and add info
#269
> Update error message on bounty submission

- src/pages/sponsor.tsx
- Optimizes images served on https://earn.superteam.fun/sponsor/
- Elements tab (srcset generation of images based on viewport), Network tab (preload)
- Resizing the viewport / through network tab
https://nextjs.org/docs/pages/api-reference/components/image
> Optimizing Images served on earn.superteam.fun/sponsor, Preloading required images (priority and eager)

- src/pages/_app.tsx
- src/theme/styles.ts
> fix: font-issues-on-safari

- package.json
- src/components/Header/Header.tsx
- yarn.lock
You can now "right click + open link in new tab" by clicking on the Earn logo in the header.
Added <Link> over the <Image> component in Header.tsx
> Added a Link to the Earn logo in the Header

- src/components/Footer/Footer.tsx
changed the copyright from 2023 to 2024 ahead of new year
> update: changed the copyright from © 2023 to © 2024

- src/features/listing-builder/components/ListingBuilder/DescriptionBuilder.tsx
Now the Description Editor Toolbar is sticky with the scroll, so user don't need to go up everytime they wanna change something
Start with `DescriptionBuilder.tsx` file
Go to Create Listing on dashboard and create a new listing
#416
> styles: make toolbar sticky

- src/features/emails/components/Winners/paymentReceivedTemplate.tsx
- src/features/listings/components/Submissions/SubmissionCard.tsx
> fix: add sanitized links for submission redirects

- .gitignore
- CONTRIBUTING.md
- README.md
it will only add one more to the local setup step on readme.md & contribution.md file and .gitignore
i rise the issue by myself #438
> docs: add prisma migration to readme

- src/pages/api/listings/index.ts
If you visit the Earn website rn, there are multiple development bounties active, closed and ongoing but none of them appear when you click on "Development" in the header.  
index.ts under api/listings
Run the server and visit /category/development and you can see the results being populated there 
Nope
> Fixed development category not showing results

- src/components/Header/LoginWrapper.tsx
- src/components/home/SideBar.tsx
Fixes hydration issues
components/home/Sidebar.tsx
run the server thats it
Solves #364
> Fixing Hydration Issues

- src/pages/category/[slug]/all.tsx
> category/[slug]/all does not show active projects 

- src/pages/listings/[type]/[slug]/winner.tsx
> fix: remove twitter og title for winner banner

- package.json
- pnpm-lock.yaml
- src/features/listing-builder/components/ListingBuilder/DescriptionBuilder.tsx
- src/styles/globals.scss
- src/utils/upload.ts
fixes: #478 
Start by reviewing the changes made in the DescriptionBuilder component file (DescriptionBuilder.tsx). Look for the modifications in the event handling and editor interaction sections.
1. Open the Listing Details box component.
2. Trigger the image input/upload event by selecting a file
3. Verify that the file is correctly extracted and processed.
I also implemented the Heading Feature which I mentioned in this comment: [LINK](https://github.com/SuperteamDAO/earn/issues/478#issuecomment-2014807093)
Add support for images in the listing description #478
https://github.com/SuperteamDAO/earn/assets/40737575/b3db61be-6534-4293-b462-d84dfda66a13
> fix:#478 added upload image feature in the listing description box

- src/components/misc/ogImageViewer.tsx
- src/pages/listings/[type]/[slug]/references.tsx
closes #413 
check the reference tab of a project listing
> fix: og images cropping

- src/features/listing-builder/components/ListingBuilder/DescriptionBuilder.tsx
> feat: chatgpt plugin link for listing builder at description

- src/pages/dashboard/listings/[slug]/edit.tsx
> fix: go to step 2 when published, edit listing

- src/features/sponsor/components/Testimonials.tsx
Fixes spelling errors in the Sponsor page (Testimonial section).
N/A
N/A
N/A
N/A
> chore: correct typos in testimonials

- src/features/sponsor/components/Stats.tsx
Fixes a spelling error in the Sponsor page (Stats section).
N/A
N/A
N/A
N/A
N/A
> chore: fix typo

- src/features/listings/components/ListingCard.tsx
- src/features/search/components/SearchModal.tsx
> chore: remove listing card wraping and search modal positioning

- src/components/home/Banner.tsx
- src/components/home/SideBar.tsx
- src/components/shared/UserMenu.tsx
- src/features/auth/components/SignIn.tsx
- src/features/comments/components/Comment.tsx
- src/features/comments/components/Comments.tsx
- src/features/feed/components/FeedCardContainer.tsx
- src/features/listings/components/ListingCard.tsx
- src/features/listings/components/ListingPage/ListingHeader.tsx
- src/features/listings/components/ListingSection.tsx
- src/features/listings/components/ListingTabs.tsx
- src/features/listings/components/Submission/SubmissionActionButton.tsx
- src/features/listings/components/WarningModal.tsx
- src/features/navbar/components/DesktopNavbar.tsx
- src/features/navbar/components/Footer.tsx
- src/features/navbar/components/Header.tsx
- src/features/navbar/components/MobileNavbar.tsx
- src/features/sponsor-dashboard/components/CreateListingModal.tsx
- src/features/sponsor-dashboard/components/Submissions/SubmissionDetails.tsx
- src/features/sponsor/components/DesktopNavbar.tsx
- src/features/sponsor/components/MobileNavbar.tsx
- src/pages/search/index.tsx
- src/pages/t/[slug]/index.tsx
> FIX: Posthog event capture corrections

- src/features/listings/components/Submission/SubmissionActionButton.tsx
I edited the submission button Ui for mobile view as it is not visible after latest update
[src/features/listings/components/Submission/SubmissionActionButton.tsx](https://github.com/SuperteamDAO/earn/compare/staging...rahulsingh2312:earn:submit-now-ui-bug?expand=1#diff-552589584b276d638fe10bdf2b6ac9cee4b3edab304a358228ff7d95f3eb8288)
Visit any bounty or Any Grant in mobile view. Compare live website and the Vercel deployment of this PR
Currently, in mobile view, the submission button is not correctly visible with this PR it will be clearly visible.
Fixes #619
> [fixes] Submit now UI bug

- src/layouts/Sponsor.tsx
- src/pages/_app.tsx
> FIX: shift entity name modal to sponsor layout

- src/pages/api/listings/v2.ts
- src/pages/index.tsx
> refactor: v2 api

- src/pages/talent-olympics.tsx
> FIX: Talent Olympics

- src/pages/talent-olympics.tsx
> chore(olympics): update discord link

- src/pages/talent-olympics.tsx
> chore(olympics): hide vault in rust track

- src/pages/talent-olympics.tsx
> chore(olympics): add correct urls for challenges

- src/pages/api/crons/discord/due-for-winners.ts
> chore(discord): earliest first for due for winners

- src/constants/index.ts
> chore(olympics): tanzania name correction

- src/features/navbar/components/Header.tsx
> chore: hide snackbar

- src/pages/talent-olympics.tsx
> chore(olympics): discord link update

- src/components/home/SideBar.tsx
> chore(olympics): hide sidebar banner

- src/features/listing-builder/components/ListingBuilder/ListingPayments.tsx
> fix(listing): data loss on update listing at payment step

- src/pages/api/grants/index.ts
> fix(grants): region filter for user logged in failing

- src/pages/api/grants/index.ts
> fix(grants): region geo locking fix

- src/features/grants/types/index.ts
- src/features/search/components/Results.tsx
- src/features/search/components/SearchModal.tsx
- src/features/search/types/index.ts
- src/features/search/utils/search.ts
- src/pages/api/search/[query].ts
- src/pages/search/index.tsx
> Feat: Grants Search

- src/features/listing-builder/components/ListingBuilder/ListingPayments.tsx
- src/features/sponsor-dashboard/components/ListingTable.tsx
- src/pages/dashboard/hackathon/index.tsx
- src/utils/rank.ts
> FIX: Listing builder draft issue across all types

- src/components/TalentBio/index.tsx
- src/features/grants/components/GrantsCard.tsx
- src/features/grants/components/GrantsHeader.tsx
- src/features/grants/queries/grants.ts
- src/features/home/components/LiveGrants.tsx
- src/features/home/components/LiveListings.tsx
- src/features/home/components/index.ts
- src/features/listing-builder/components/CreateListing.tsx
- src/features/listing-builder/components/ListingBuilder/DescriptionBuilder.tsx
- src/features/listing-builder/components/ListingBuilder/QuestionBuilder.tsx
- src/features/listings/components/ListingPage/ExtraInfoSection.tsx
- src/features/listings/components/ListingPage/ListingHeader.tsx
- src/features/listings/components/ListingPage/RegionLabel.tsx
- src/features/listings/components/ListingPage/RightSideBar.tsx
- src/features/listings/components/Submission/SubmissionActionButton.tsx
- src/features/listings/components/SubmissionsPage/SubmissionCard.tsx
- src/features/listings/components/SubmissionsPage/SubmissionPage.tsx
- src/features/listings/queries/listings.ts
- src/features/listings/utils/index.ts
- src/layouts/Grants.tsx
- src/layouts/Listing.tsx
- src/pages/api/grants/index.ts
- src/pages/api/listings/index.ts
- src/pages/listings/[type]/[slug]/index.tsx
- src/styles/globals.scss
- src/svg/pulse-icon.tsx
> fix(new-listings): live grants, pulse animation, UX fixes

- src/features/listings/components/Submission/SubmissionModal.tsx
> fix(hackathon): remove yt/loom validation

- src/pages/api/listings/announce/[id].ts
> feat(airtable): sync to airtable on winners announce

- src/features/navbar/components/BountySnackbar.tsx
- src/layouts/Listing.tsx
> feat(snackbar): caution sponsors

- src/components/shared/LinkTextParser.tsx
- src/features/listing-builder/components/ListingBuilder/DescriptionBuilder.tsx
- src/features/listings/components/ListingPage/RightSideBar.tsx
- src/features/sponsor-dashboard/components/GrantApplications/ApplicationDetails.tsx
- src/features/sponsor-dashboard/components/Submissions/Details.tsx
- src/pages/api/listings/update/[id].ts
- src/styles/globals.scss
> [dont merge] FIX: Bugs, description builder, link colors, # application copy and more

- prisma/schema.prisma
- src/features/emails/utils/sendEmailNotification.ts
- src/features/feed/components/Feed.tsx
- src/features/feed/components/FeedCardContainer.tsx
- src/features/feed/components/WinnerFeedImage.tsx
- src/features/feed/components/grantCard.tsx
- src/features/feed/components/index.ts
- src/features/feed/types/index.ts
- src/pages/api/feed/get.ts
- src/pages/api/grant-application/like.ts
- src/pages/api/pow/like.ts
- src/pages/api/submission/like.ts
- src/pages/api/user/info.ts
- src/pages/t/[slug]/index.tsx
- src/services/likeService.ts
> FEAT: Grant Applications to Activity Feed and User Profile with Likes

- src/features/feed/components/Feed.tsx
- src/features/home/components/VibeCard.tsx
> CHORE: Vibe card add to mobile views

- src/constants/exclusiveSponsors.ts
- src/pages/api/listings/sponsor.ts
> fix(sponsor): show privates

- src/lib/earncognitoClient.ts
- src/pages/api/listings/announce/[id].ts
- src/pages/api/listings/create.ts
- src/pages/api/listings/update/[id].ts
> FEAT: Earncognito Client 

- prisma/schema.prisma
- src/features/grants/components/GrantApplicationModal.tsx
- src/features/grants/utils/index.ts
- src/features/sponsor-dashboard/components/GrantApplications/ApplicationDetails.tsx
- src/pages/api/grant-application/create.ts
> feat(grant-applications): required twitter field

- src/features/talent/components/onboarding-form/YourLinks.tsx
- src/pages/new/talent.tsx
> [MEREG] feat(onboarding): remove success modal on talent fill, direct redirect

- package.json
- pnpm-lock.yaml
- src/features/listing-builder/components/ListingBuilder/DescriptionBuilder.tsx
> feat(listing-builder): added image dropzone for image upld

- prisma/schema.prisma
- src/features/emails/utils/sendEmailNotification.ts
- src/features/listings/components/Submission/PublishResults.tsx
- src/features/sponsor-dashboard/components/GrantApplications/ApplicationDetails.tsx
- src/features/sponsor-dashboard/components/GrantApplications/Modals/RejectAllModal.tsx
- src/features/sponsor-dashboard/components/Submissions/Modals/RejectAllModal.tsx
- src/features/sponsor-dashboard/components/Submissions/Modals/RejectModal.tsx
- src/features/sponsor-dashboard/components/Submissions/Modals/index.ts
- src/features/sponsor-dashboard/components/Submissions/SelectWinner.tsx
- src/features/sponsor-dashboard/components/Submissions/SubmissionList.tsx
- src/features/sponsor-dashboard/components/Submissions/SubmissionPanel.tsx
- src/features/sponsor-dashboard/components/Submissions/index.ts
- src/features/sponsor-dashboard/index.ts
- src/features/sponsor-dashboard/mutations/index.ts
- src/features/sponsor-dashboard/mutations/useRejectSubmissions.ts
- src/features/sponsor-dashboard/mutations/useToggleWinner.ts
- src/interface/submission.ts
- src/pages/api/listings/announce/[id].ts
- src/pages/api/sponsor-dashboard/grants/update-application-status.ts
- src/pages/api/sponsor-dashboard/submission/reject.ts
- src/pages/dashboard/grants/[slug]/applications.tsx
- src/pages/dashboard/hackathon/[listing]/submissions.tsx
- src/pages/dashboard/listings/[slug]/submissions.tsx
> [MERGE] feat(projects): multi-reject project applications

- prisma/schema.prisma
- src/features/auth/types/index.ts
- src/features/auth/utils/withSponsorAuth.ts
- src/features/listing-builder/components/CreateListing.tsx
- src/features/listings/components/Submission/SubmissionActionButton.tsx
- src/features/listings/types/index.ts
- src/features/listings/utils/index.ts
- src/features/navbar/components/BountySnackbar.tsx
- src/features/sponsor-dashboard/components/ListingTable.tsx
- src/layouts/Listing.tsx
- src/pages/api/listings/create.ts
- src/pages/api/listings/update/[id].ts
- src/pages/api/sponsor-dashboard/listings/index.ts
> [MERGE]feat(dashboard): unverified status, verifying refactor, god mode to edit

- src/features/home/components/RelatedListings.tsx
- src/features/home/components/index.ts
- src/features/listings/components/ListingPage/RightSideBar.tsx
- src/features/listings/queries/index.ts
- src/features/listings/queries/related-listing.ts
- src/pages/api/listings/[listingId]/related.tsx
> feat(listings): related listings added

- src/features/sponsor-dashboard/components/Submissions/SubmissionList.tsx
> fix(multireject): hide for bounties

- src/constants/index.ts
> chore: add degod token

- src/pages/api/search/[query].ts
> chore: hackathon query to search added

- prisma/schema.prisma
- src/features/listing-builder/components/CreateListing.tsx
- src/features/listing-builder/components/ListingBuilder/ListingBasic.tsx
- src/features/listing-builder/store/index.ts
- src/features/listing-builder/types/index.ts
- src/features/listings/types/index.ts
- src/pages/api/listings/announce/[id].ts
> revert: #5bb2396e

- src/pages/api/listings/[listingId]/related.tsx
> fix(related-listing): handle case for empty subskills

- src/features/sponsor-dashboard/components/Submissions/Modals/RejectAllModal.tsx
- src/features/sponsor-dashboard/components/Submissions/SelectWinner.tsx
- src/features/sponsor-dashboard/mutations/useRejectSubmissions.ts
- src/pages/api/sponsor-dashboard/submission/reject.ts
- src/pages/dashboard/listings/[slug]/submissions.tsx
> feat: multi and single page select for project applications

- src/components/shared/ogImageViewer.tsx
- src/features/listing-builder/components/CreateListing.tsx
- src/features/listing-builder/components/ListingBuilder/DescriptionBuilder.tsx
- src/features/listing-builder/components/ListingBuilder/ReferenceCard.tsx
- src/features/listing-builder/store/index.ts
- src/features/listings/components/ListingPage/ReferenceCard.tsx
- src/features/listings/types/index.ts
- src/pages/grants/[slug]/references.tsx
- src/pages/listings/[type]/[slug]/references.tsx
- src/pages/templates/listings/[slug]/references.tsx
> feat: reference titles added

- src/features/sponsor-dashboard/components/Submissions/SubmissionList.tsx
- src/pages/dashboard/grants/[slug]/applications.tsx
- src/pages/dashboard/listings/[slug]/submissions.tsx
> feat(dasboard): keyboard shortcuts to switch pages and applications

- prisma/schema.prisma
- src/pages/api/auth/[...nextauth].ts
- src/pages/api/email/manual/welcome-sponsor.ts
- src/pages/api/email/manual/welcome-talent.ts
- src/pages/api/member-invites/send.ts
> DONT MERGE feat: blocked emails

- src/pages/t/[slug]/index.tsx
> chore(talent): profile hide properties that aren't filled

- src/pages/api/sponsor-dashboard/grants/update-ship-progress.ts
> fix(dashboard): fix application recipient table earn id field name

- src/layouts/Sponsor.tsx
> fix(dashboard): entity modal to not show to gods

- src/features/sponsor-dashboard/components/InfoBox.tsx
> fix(dashboard): remove json parse for content infobox

- src/features/sponsor-dashboard/components/GrantApplications/ApplicationDetails.tsx
- src/features/sponsor-dashboard/components/GrantApplications/ApplicationList.tsx
- src/features/sponsor-dashboard/components/InfoBox.tsx
> fix(dashboard): overflow text on application details

- src/features/feed/components/FeedCardContainer.tsx
> fix(comments): infeed counts increments 2 for single comment

- src/features/listing-builder/components/ListingBuilder/ListingBasic.tsx
> fix(listing-builder): multiple switches not operating in basics step

- prisma/schema.prisma
> chore(schema): add db.Text for markdown fields

- src/features/listings/components/Submission/SubmissionModal.tsx
> fix(submission-modal): edit autofill

- src/constants/index.ts
> main to staging

- prisma/schema.prisma
- src/pages/api/grants/index.ts
- src/pages/api/homepage/grants.ts
> feat: grants to have any country as region

- src/features/home/queries/grants.ts
- src/features/listings/utils/region.ts
- src/pages/api/grants/index.ts
- src/pages/api/homepage/for-you.ts
- src/pages/api/homepage/listings.ts
- src/pages/api/listings/index.ts
- src/pages/api/listings/regions.ts
- src/pages/index.tsx
> fix: region headache for listings and grants

- src/features/listings/utils/region.ts
- src/pages/api/grants/index.ts
- src/pages/api/homepage/for-you.ts
- src/pages/api/listings/index.ts
- src/pages/index.tsx
> fix: region issue try 2

- src/features/listing-builder/components/Form/Rewards/Types/Fixed.tsx
- src/features/listing-builder/hooks/index.ts
- src/features/listing-builder/types/schema.ts
> fix: rewards empty instead of nan

- src/pages/api/user/edit.ts
- src/pages/t/[slug]/edit.tsx
> fix: edit profile

- src/features/talent/schema/index.ts
> fix: remove community value validation in profile schema

- src/components/ui/select.tsx
> fix: select z-index

- src/features/grants/components/GrantEntry.tsx
- src/pages/grants/index.tsx
> fix: grants homepage mobile

- src/features/grants/components/GrantEntry.tsx
> fix: grants homepage mobile width box

- src/features/grants/components/GrantApplicationModal.tsx
- src/features/social/utils/extractUsername.ts
- src/features/social/utils/regex.ts
- src/features/sponsor-dashboard/components/GrantApplications/ApplicationDetails.tsx
- src/pages/api/grant-application/create.ts
- src/pages/api/grant-application/update.ts
> fix: telegram, twitter link in POC field

- src/features/grants/components/GrantApplicationModal.tsx
- src/features/grants/utils/grantApplicationSchema.ts
- src/features/social/components/SocialInput.tsx
- src/pages/api/grant-application/create.ts
- src/pages/api/grant-application/update.ts
> fix: twitter username capture grant application modal

- src/features/listing-builder/hooks/index.ts
> fix: deadline draft time change

- src/features/home/components/UserStatsBanner.tsx
- src/features/navbar/components/Footer.tsx
> chore: Cleaned Footer & Personalized UserStats Banner

- src/lib/earncognitoClient.ts
> fix: remove 5s limit on earncognitoClient

- src/features/listing-builder/components/Form/PrePublish/Modal.tsx
> fix: disable fndn pay toggle for project

- src/pages/api/sponsor-dashboard/local-profiles/index.ts
> chore: local profile try normalize

- src/features/sponsor-dashboard/queries/local-profiles.ts
- src/pages/api/sponsor-dashboard/local-profiles/index.ts
- src/pages/dashboard/local-profiles/index.tsx
> chore: local profile add region param for caching

- src/pages/api/sponsor-dashboard/local-profiles/index.ts
> chore: local profile trying as map

- src/features/listings/components/Submission/SubmissionDrawer.tsx
> fix: link and tweet field of submission to be reactive

- src/features/listings/components/Submission/SubmissionDrawer.tsx
> fix: project quetion label submission form

- src/features/talent/components/onboarding-form/fields/Location.tsx
- src/features/talent/schema/index.ts
- src/pages/t/[slug]/edit.tsx
> fix: make location required again

- src/features/listings/components/ListingPage/PrizesList.tsx
- src/utils/rank.ts
> fix: podium rank bonus on wrong index

- src/features/listings/components/ListingPage/PrizesList.tsx
- src/utils/rank.ts
> fix: bonus rank showing as bonus for rightsidebar

- src/constants/tokenList.ts
> chore: change solayer icon link

- src/pages/listing/[slug]/index.tsx
> redirect: passion-piece to corrrect url

- package.json
- pnpm-lock.yaml
- src/pages/_app.tsx
> fix: attempt to fix posthog client side exception

- src/features/listing-builder/atoms/index.ts
- src/features/listing-builder/components/Form/Rewards/Types/Podiums.tsx
- src/features/listing-builder/hooks/index.ts
- src/features/listing-builder/types/schema.ts
- src/pages/api/listings/draft.ts
> fix: maxbonusspot to 0 while draft changes

- src/components/ui/wallet-connect-field.tsx
- src/pages/_app.tsx
> fix: wallet connect for listing

- next.config.ts
> fix: csr policies breaking image upload in listing builder

- src/app/api/grant-application/update/route.ts
- src/features/grants/components/GrantApplicationModal.tsx
> fix: grant application update failing for telegram invalid link

- src/features/grants/components/GrantApplicationModal.tsx
- src/features/grants/utils/grantApplicationSchema.ts
- src/features/social/utils/extractUsername.ts
> fix: null being passed to extractSocialUsername

- src/layouts/Sponsor.tsx
- src/pages/signup.tsx
> fix: redirection after signup as member

- prisma/schema.prisma
- src/app/api/listings/announce/[id]/route.ts
- src/app/api/sponsor-dashboard/grant-application/ai/commit-reviewed/route.ts
- src/app/api/sponsor-dashboard/grant-application/ai/review/route.ts
- src/app/api/sponsor-dashboard/grant-application/ai/unreviewed/route.ts
- src/app/api/sponsor-dashboard/listing/[id]/total-payments-made/route.ts
- src/features/listing-builder/utils/listingToStatus.ts.ts
- src/features/listings/utils/status.ts
- src/features/sponsor-dashboard/components/Modals/VerifyPayment.tsx
- src/features/sponsor-dashboard/components/Submissions/SelectWinner.tsx
- src/features/sponsor-dashboard/queries/total-payments-made.ts
- src/pages/api/hackathon/listings.ts
- src/pages/api/listings/unpublish/[id].ts
- src/pages/api/listings/update/[id].ts
- src/pages/api/sponsor-dashboard/[slug]/listing.ts
- src/pages/api/sponsor-dashboard/listings/index.ts
- src/pages/api/sponsor-dashboard/listings/verify-external-payment.ts
- src/pages/api/sponsor-dashboard/submission/add-payment.ts
- src/pages/api/sponsor-dashboard/submission/toggle-winner.ts
> refactor: remove total winners selected and total payments made, infer it from true source instead

- src/features/wallet/components/withdraw/WithdrawFundsFlow.tsx
> chore: add userid in withdraw error logs to debug

- src/layouts/Listing.tsx
> fix: og listing

- src/pages/listing/[slug]/index.tsx
> fix: og attempt 2

- src/pages/_app.tsx
> fix: server side rendering for listings

- src/pages/api/sponsor-dashboard/local-profiles/index.ts
> chore: local profile log

- src/constants/tokenList.ts
> chore: fix edwin token

- src/features/sponsor-dashboard/components/GrantApplications/ApplicationHeader.tsx
- src/utils/formatNumberWithSuffix.ts
> fix: grant range showing '-'

- src/features/auth/utils/getPrivyToken.ts
- src/features/auth/utils/getSponsorSession.ts
- src/features/auth/utils/getUserSession.ts
- src/features/auth/utils/withAuth.ts
- src/features/auth/utils/withSponsorAuth.ts
- src/utils/safeStringify.ts
> chore: add bunch of logging to privy auth check

- src/components/modals/AiReviewFeature.tsx
- src/pages/dashboard/grants/[slug]/applications.tsx
> chore: add grant announcement modal

- src/features/listing-builder/components/Form/EligibilityQuestions.tsx
> fix: eligibility listing builder slicing Qs

- next.config.ts
- src/features/home/components/SideBar.tsx
- src/features/home/components/SidebarBanner.tsx
- src/features/listing-builder/components/Form/TitleAndType.tsx
- src/features/listing-builder/types/schema.ts
- src/features/listings/components/ListingPage/CompensationAmount.tsx
- src/features/listings/components/ListingPage/ExtraInfoSection.tsx
- src/features/listings/components/ListingPage/PrizesList.tsx
- src/features/listings/components/ListingPage/RightSideBar.tsx
- src/features/listings/components/Submission/SubmissionDrawer.tsx
- src/features/listings/types/index.ts
- src/features/listings/utils/submissionFormSchema.ts
- src/features/navbar/components/DesktopNavbar.tsx
- src/features/navbar/components/MobileNavbar.tsx
- src/features/sponsor-dashboard/components/InfoBox.tsx
- src/pages/api/hackathon/get.ts
- src/pages/api/listings/details/[slug].ts
- src/pages/hackathon/mobius.tsx
- src/pages/hackathon/talent-olympics.tsx
- src/queries/hackathon.ts
> Hackathon: Mobius

- src/features/comments/components/Comment.tsx
> fix: space between reply numebrs and reply  label

- src/pages/hackathon/mobius.tsx
> fix: twitter image for mobius correctly

- src/features/home/components/SideBar.tsx
- src/features/navbar/components/DesktopNavbar.tsx
- src/features/navbar/components/MobileNavbar.tsx
- src/pages/hackathon/mobius.tsx
> make mobius live

- src/features/auth/utils/getPrivyToken.ts
- src/lib/api.ts
> auth: check for headers and add privy app id to headers

- src/features/listings/components/Submission/SubmissionActionButton.tsx
> chore: logic of userSubmissionQuery enabled update

- prisma/schema.prisma
> chore: change pow link type to text from string to allow longer links

- src/components/shared/SuperteamCombobox.tsx
- src/features/listing-builder/components/Form/PrePublish/Modal.tsx
- src/features/listing-builder/components/Form/PrePublish/ReferredBy.tsx
- src/features/listing-builder/types/schema.ts
- src/features/listing-builder/utils/form.ts
- src/features/listings/types/index.ts
- src/pages/api/listings/draft.ts
- src/pages/api/listings/publish/[id].ts
- src/pages/api/listings/update/[id].ts
> feat: referred by on listing builder

- src/pages/hackathon/redacted.tsx
> chore: redacted updates

- src/features/navbar/components/UserMenu.tsx
> fix: closing of email preference modal on hash link

- src/pages/hackathon/mobius.tsx
> chore: mobius faq update

- src/pages/hackathon/mobius.tsx
> chore: update faq copy

- src/features/home/components/NavTabs.tsx
> fix: navpill mobius make better

- src/features/home/components/Banner/SponsorBanner.tsx
> fix: sponsor banner button

- src/components/shared/ogImageViewer.tsx
> fix: OG image viewer for references

- src/pages/listing/[slug]/index.tsx
> chore: add redacted banner in redacted tracks

- src/features/home/components/Banner/SponsorBanner.tsx
- src/utils/number.ts
> chore: add round to nearest to sponsor banner

- src/features/sponsor-dashboard/components/ApplicationsTab.tsx
> fix: pagination grant applications sponsor dashboard

- src/pages/api/sponsor-dashboard/local-profiles/export.ts
> fix: unofficial superteam local profile export

- src/pages/api/sponsor-dashboard/active-hackathons.ts
> fix: active hackathon dont check for god mode hackathon id

- src/features/listing-builder/components/ListingBuilder.tsx
> fix: incosistent state refresh of listing builder

- src/pages/api/sponsor-dashboard/grants/[slug]/applications.ts
> feat: support sorting in grant applications across pagination

- src/features/listing-builder/components/Form/EligibilityQuestions.tsx
> chore: make sure hackathon Qs that are edited are not overwritten

- src/features/home/components/SidebarBanner.tsx
> chore: sidebar banner safari misalignment fix

- src/components/shared/SupportFormDialog.tsx
- src/features/navbar/components/UserMenu.tsx
> chore: add posthog events for support form

- src/pages/_app.tsx
> chore: enable recording so posthog takes care of conditionals

- src/features/listings/components/ListingPage/PrizesList.tsx
> chore: show 2 decimals in listing page sidebar podiums

- src/pages/hackathon/breakout.tsx
> chore: show 0 decimals in breakout total prizes

- src/features/sponsor-dashboard/components/PublishResults.tsx
> fix: project publish announce winner modal copy

- src/features/listing-builder/atoms/index.ts
- src/features/listing-builder/components/Form/DescriptionAndTemplate/DescriptionAndTemplate.tsx
- src/features/listing-builder/components/Form/Skills.tsx
- src/features/listing-builder/hooks/index.ts
> fix: start from scratch

- src/app/api/sponsor-dashboard/grants/update-tranche-status/route.ts
- src/features/grants/utils/addOnboardingInfoToAirtable.ts
- src/features/grants/utils/addPaymentInfoToAirtable.ts
- src/features/grants/utils/createTranche.ts
- src/features/grants/utils/syncGrantApplicationWithAirtable.ts
> chore: add logs

- src/app/api/sponsor-dashboard/ai-generate/description/route.ts
> chore: change from 2.5 flash to o4 mini high for description

- src/components/ui/copy-tooltip.tsx
> chore: remove relative from copybutton trigger

- .eslintrc.json
- src/pages/api/hackathon/listings.ts
> chore: status fixed for hackathon dashboard page

- prisma/schema.prisma
- src/components/modals/EntityNameModal.tsx
- src/constants/tokenList.ts
- src/features/listings/utils/query-builder.ts
- src/features/sponsor-dashboard/components/Banner.tsx
- src/features/sponsor-dashboard/components/Modals/VerifyPayment.tsx
- src/features/sponsor-dashboard/components/Scouts/ScoutTable.tsx
- src/features/sponsor-dashboard/types.ts
- src/features/sponsor-dashboard/utils/paymentRPCValidation.ts
- src/layouts/Sponsor.tsx
- src/pages/api/feed/get.ts
- src/pages/new/sponsor.tsx
> staging to main

- src/features/listings/components/Submission/SubmissionDrawer.tsx
> fix: terms of use click to submit solved

- src/pages/dashboard/local-profiles/index.tsx
> fix: unofficial superteams local profiles not displaying name currectly

- src/layouts/Sponsor.tsx
> chore: lower case check for stlead v region for local profile visibility

- src/features/sponsor-dashboard/utils/statusColorMap.ts
> fix: spam color being different

- src/features/sponsor-dashboard/components/Submissions/SpamButton.tsx
> fix: hacky spam fix for not opening

- src/features/listings/utils/submissionFormSchema.ts
> chore: allow nullable optional value for eligibility answers schema

- src/features/announcements/components/SponsorAnnouncements.tsx
> chore: hide announcement modal for non st sponsors

- src/app/api/image/delete/route.ts
> fix: make sure image is not used anywhere before deleting

- src/pages/api/user/update.ts
> chore: try fixing user update by separating update and select
